### ISSUE TITLE
Bug when trying to append a string to a file using `echo`

### ISSUE THREAD

**Issue by aquaslvt** [project-novagon/freeshell#2]
## Steps to replicate
`echo 'meowmeow' >> meow`

## Result
```
Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1
	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
	at kotlin.io.LineReader.decode(Console.kt:244)
	at kotlin.io.LineReader.readLine(Console.kt:212)
	at kotlin.io.ConsoleKt.readLine(Console.kt:170)
	at kotlin.io.ConsoleKt.readlnOrNull(Console.kt:163)
	at kotlin.io.ConsoleKt.readln(Console.kt:152)
	at MainKt.main(Main.kt:25)
	at MainKt.main(Main.kt)
```

**Comment by dxvv-software** [comment]
![image](https://github.com/project-novagon/freeshell/assets/88238063/dc71471d-3338-497d-a692-aba8e6ca258f)
this is the result for me

**Comment by aquaslvt** [comment]
weird

**Comment by aquaslvt** [comment]
did you `touch meow` first?

**Comment by dxvv-software** [comment]
i'm gonna try that

**Comment by dxvv-software** [comment]
(novagondeveloper @ novagon at /home/novagondeveloper ) ~> echo 'meow' >> meow
'meow' >> meow
still does the same thing

**Comment by dvnlx** [comment]
(novagondeveloper @ novagon at /home/novagondeveloper ) ~> echo 'meow' >> meow
'meow' >> meow
still does the same thing

**Comment by aquaslvt** [comment]
closed issue because something else is triggering the bug and is currently unknown

**Comment by aquaslvt** [comment]
yeah lemme close this as "can't repro"
